JFLAGS = -g
JCC = javac
SOURCE_PATH= ./James ./Joel ./Zach ./Mohammed ./Josh ./mainPack ./Test
.SUFFIXES: .java .class
.java.class:
        $(JC) $(JFLAGS) $*.java

CLASSES = \
	Display.java\
	DisplayImpl.java\
	AI.java\
	DumbAI.java\
	Node.java\
	NodeImpl.java\
	NTree.java\
	NTreeImpl.java\
	SmartAI.java\
	SmartAIImpl.java\
	UserInput.java\
	Controls.java\
	ControlsImpl.java\
	DummyGameBoard.java\
	DummyGameBoardImpl.java\
	GameBoard.java\
	GameBoardImpl.java\
	main.java\
	StateCheck.java\
	StateCheckImpl.java\
	AbstractGeneralControls.java\
	GeneralControls.java\
	GeneralControlsTester.java\
	P.java\
	PLAYER.java\
	DumbAITest.java\
	DummyGameBoardImplTest.java\
	JUnitTestForGeneralControlsImpl.java\
	NodeImplTest.java\
	NTreeTestCase.java\
	SmartAIImplTest.java\
	TestStateCheck.java\
	DummyControl.java\
	GameEngine.java\
	GameEngineImpl.java

default: classes

classes: $(CLASSES:.java=.class)

clean:
        $(RM) *.class